
spring:
  h2:
    console:
      enabled: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true